version: '3.4'

services:
  dockernodejs:
    image: dockernodejs
    build:
      context: docker-nodejs
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
